### ISSUE TITLE
Add readme.md

### ISSUE THREAD

**Issue by Anubhav-Bhargava** [iiittrichy/IIIT-Trichy-Official-Website#1]
Please add installation instructions and other relevant sections

**Comment by abhijeetps** [comment]
See #4 .

**Comment by MadhavBahlMD** [comment]
I can make a README.md if you want :D 

Assign me to the issue :)

**Comment by Anubhav-Bhargava** [comment]
Closed via #4

**Comment by Anubhav-Bhargava** [comment]
Closed via #4
