### ISSUE TITLE
Add Auto dropdown for Menu Items

### ISSUE THREAD

**Issue by Anubhav-Bhargava** [iiittrichy/IIIT-Trichy-Official-Website#2]
**Observed Behaviour**
Currently, we have to click on each menu item to see the listed items. 

**Expected Behaviour**
Auto drop down on  mouse hover

**Comment by MadhavBahl** [comment]
Hey @Anubhav-Bhargava 
I can fix this, assign me to the issue :)

**Comment by Anubhav-Bhargava** [comment]
Hey @MadhavBahlMD 
You can start working on this issue!!

**Comment by MadhavBahl** [comment]
Sure, will do it as soon as I find time, and generate a PR
